"""Report generation for dynamic agent tool."""

from __future__ import annotations

from datetime import datetime
from typing import Dict, List


def generate_diagnostic_report(analysis_result: dict, agent_descriptions: List[dict]) -> str:
    report = f"""# 🚀 Company Efficiency Diagnostic Report
Generated: {datetime.now().strftime('%Y-%m-%d %H:%M:%S')}

## 📊 Executive Summary
{analysis_result['data_confirmation']}

**Key Findings:**
- Total Inefficiencies: {analysis_result['summary']['total_inefficiencies']}
- Critical Issues: {analysis_result['summary']['critical_issues']}
- Warning Issues: {analysis_result['summary']['warning_issues']}
- AI Agents Deployed: {analysis_result['summary']['agents_needed']}

## 📈 KPI Analysis

| KPI | Current Value | Benchmark | Status |
|-----|---------------|-----------|--------|
"""

    for kpi, value in analysis_result['kpis'].items():
        benchmark = analysis_result['benchmarks'].get(kpi, 'N/A')
        if isinstance(value, (int, float)):
            if value < float(str(benchmark).replace('$', '').replace('%', '').split('-')[0]) * 0.8:
                status = "🔴 Critical"
            elif value < float(str(benchmark).replace('$', '').replace('%', '').split('-')[0]) * 0.9:
                status = "🟡 Warning"
            else:
                status = "🟢 Good"
        else:
            status = "⚪ N/A"

        report += f"| {kpi} | {value:.1f}% | {benchmark} | {status} |\n"

    report += """
## ⚠️ Identified Inefficiencies

"""

    for i, inefficiency in enumerate(analysis_result['inefficiencies'], 1):
        severity_emoji = "🔴" if inefficiency['severity'] == 'critical' else "🟡"
        report += f"""
### {i}. {inefficiency['kpi_name']} {severity_emoji}
- **Current**: {inefficiency['current_value']:.1f}%
- **Benchmark**: {inefficiency['benchmark']:.1f}%
- **Severity**: {inefficiency['severity'].upper()}
- **Issue**: {inefficiency['description']}
- **Root Cause**: {inefficiency['root_cause']}
- **Recommended Agent**: {inefficiency['recommended_agent']}
"""

    report += """
## 🤖 Generated Specialized AI Agents

"""

    for i, agent in enumerate(agent_descriptions, 1):
        priority_emoji = "🔴" if agent['priority'] == 'critical' else "🟡" if agent['priority'] == 'high' else "🟢"
        report += f"""
### {i}. {agent['type']} {priority_emoji}
- **Goal**: {agent['goal']}
- **Priority**: {agent['priority'].upper()}
- **Capabilities**: {', '.join(agent['capabilities'][:3])}...
"""

    report += """
## 🎯 Implementation Roadmap

### Immediate Actions (0-30 days)
1. Deploy critical priority agents first
2. Set up monitoring and tracking systems
3. Establish baseline metrics for each agent
4. Create cross-functional optimization teams

### Short-term Goals (1-3 months)
1. Implement agent-specific optimization strategies
2. Monitor KPI improvements and adjust approaches
3. Train teams on new processes and systems
4. Measure and report on agent performance

### Long-term Objectives (3-12 months)
1. Achieve industry benchmark performance
2. Scale successful optimization strategies
3. Develop competitive advantages
4. Implement continuous improvement processes

## 📋 Next Steps
1. Review and approve generated agent configurations
2. Deploy agents via the multi-agent architecture
3. Provide additional data to refine agent tasks
4. Monitor progress and adjust strategies as needed

---
*This report was generated by the Company Efficiency Optimizer using advanced AI analysis.*
"""

    return report
